DefaultContentLanguage = "en"
author = "Steve Francia"
baseURL = "https://ed-orlando07-home.netlify.com"
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 1
theme = "casper3"
title = "Hugo Themes"
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "https://ed-orlando07.netlify.app/"
weight = 10
[params]
description = "Data Discovery with R and Tableau"
facebook = ""
github = "https://github.com/jonathanjanssens"
logo = "/images/ghost-transparent.png"
mainSections = ["post"]
twitter = "https://twitter.com"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
